import type { SpriteResolution } from '../ui/stores/settings';
import { HIGH_RES_KEYS, LOW_RES_KEYS } from '../data/spriteKeys';

const BASE = (import.meta.env.VITE_ASSET_BASE_URL ?? '') as string;

function buildUrl(resolution: SpriteResolution, subpath: string): string {
  return `${BASE}/assets/${resolution === 'high' ? 'sprites-hires' : 'sprites'}/${subpath}`;
}

/**
 * Returns the CDN-relative URLs for a biome's packed texture atlas.
 * Atlas files are generated by the ComfyUI sprite pipeline and packed via scripts/pack-atlas.mjs.
 * Naming convention: mine_atlas_<biomeId>.{json,webp}
 *
 * DD-V2-189: TextureAtlasLRU enforces the 3-atlas max; this function provides the URLs.
 *
 * @param biomeId - The biome ID (e.g. 'surface', 'volcanic')
 * @returns Object with json and image URL paths
 */
export function getBiomeAtlasUrl(biomeId: string): { json: string; image: string } {
  return {
    json:  `${BASE}/assets/atlases/mine_atlas_${biomeId}.json`,
    image: `${BASE}/assets/atlases/mine_atlas_${biomeId}.webp`,
  }
}

/**
 * Returns the Phaser texture key for a biome's packed atlas.
 *
 * @param biomeId - The biome ID (e.g. 'surface', 'volcanic')
 * @returns The texture key string used in Phaser's texture manager
 */
export function getBiomeAtlasKey(biomeId: string): string {
  return `mine_atlas_${biomeId}`
}

/**
 * Detects WebP support at runtime. True on Chrome/Edge/Firefox 65+; false on older Safari.
 *
 * @returns True if WebP is supported in the current browser
 */
export function supportsWebP(): boolean {
  try {
    const c = document.createElement('canvas')
    c.width = 1; c.height = 1
    return c.toDataURL('image/webp').startsWith('data:image/webp')
  } catch (_) { return false }
}

/**
 * Get sprite URLs for the specified resolution.
 * Returns a mapping of sprite key → public URL.
 * @param resolution - The desired sprite resolution ('low' or 'high')
 * @returns A record mapping sprite keys to their URL strings
 */
export function getSpriteUrls(resolution: SpriteResolution): Record<string, string> {
  return getSpriteUrlsForBiome(resolution, null);
}

/**
 * Get sprite URLs filtered to only include shared sprites plus the specified biome's tiles.
 * Biome tile subpaths contain 'biomes/' and are named like: tiles/biomes/tectonic_scar_rock_07.png
 * Non-biome sprites (dome, characters, items, icons, ui, autotile, block_*, crack_*, etc.) are always included.
 *
 * @param resolution - 'low' or 'high'
 * @param biomeId - The biome ID to include tiles for (e.g. 'tectonic_scar'), or null for all biomes
 * @param secondaryBiomeId - Optional secondary biome ID for dual-biome blended layers
 */
export function getSpriteUrlsForBiome(
  resolution: SpriteResolution,
  biomeId: string | null,
  secondaryBiomeId?: string | null
): Record<string, string> {
  const keys = resolution === 'high' ? HIGH_RES_KEYS : LOW_RES_KEYS;
  const result: Record<string, string> = {};

  for (const [key, subpath] of Object.entries(keys)) {
    // Biome-specific tiles live under tiles/biomes/
    if (subpath.includes('biomes/') && biomeId !== null) {
      const filename = subpath.split('/').pop()!;
      const matchesPrimary = filename.startsWith(biomeId + '_') || filename === biomeId + '.png';
      const matchesSecondary = secondaryBiomeId
        ? (filename.startsWith(secondaryBiomeId + '_') || filename === secondaryBiomeId + '.png')
        : false;
      if (!matchesPrimary && !matchesSecondary) continue;
    }

    result[key] = buildUrl(resolution, subpath);
  }

  return result;
}
