/**
 * Drizzle ORM schema definitions for the Terra Gacha database.
 * Uses SQLite dialect for development (better-sqlite3).
 * All timestamps are stored as Unix epoch integers (milliseconds).
 */

// ── PostgreSQL jsonb migration plan (DD-V2-209) ───────────────────────────────
//
// When migrating from SQLite to PostgreSQL, the following columns should be
// converted from TEXT (JSON string) to JSONB for native indexing and querying:
//
//   saves.save_data          → jsonb  (full PlayerSave document)
//   leaderboards.metadata    → jsonb  (optional dive metadata)
//   analytics_events.properties → jsonb  (event property bag)
//   fact_packs.pack_data     → jsonb  (array of fact objects)
//
// Additionally, the saves table will be split into sub-document columns for
// efficient partial updates and field-level conflict resolution (DD-V2-214):
//
//   save_data_progression    jsonb  — { layer, minerals, artifacts, relics }
//   save_data_learning       jsonb  — { sm2Cards, masteredFacts, streaks }
//   save_data_dome           jsonb  — { upgrades, floors, pets, farm }
//   save_data_settings       jsonb  — { audio, language, accessibility }
//   save_data_meta           jsonb  — { version, clientTimestamp, sessionId }
//
// The PostgreSQL equivalent CREATE TABLE for saves would be:
//
//   CREATE TABLE saves (
//     id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
//     user_id              UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
//     version              INTEGER NOT NULL DEFAULT 1,
//     profile_id           TEXT NOT NULL DEFAULT 'default',
//     save_data_progression JSONB,
//     save_data_learning   JSONB,
//     save_data_dome       JSONB,
//     save_data_settings   JSONB,
//     save_data_meta       JSONB,
//     created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
//     updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
//   );
//   CREATE INDEX idx_saves_user_id_created ON saves(user_id, created_at DESC);
//
// Analytics columns for PostgreSQL (partitioned by month for retention):
//
//   CREATE TABLE analytics_events (
//     id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
//     session_id   TEXT NOT NULL,
//     event_name   TEXT NOT NULL,
//     properties   JSONB NOT NULL,
//     platform     TEXT,
//     app_version  TEXT,
//     user_id      UUID REFERENCES users(id) ON DELETE SET NULL,
//     created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
//   ) PARTITION BY RANGE (created_at);
//
// See server/src/db/pgReadiness.ts for migration utilities and dual-write plan.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * TypeScript types for future PostgreSQL jsonb sub-document columns.
 * These represent the decomposed structure of PlayerSave for field-level sync.
 * Not used at runtime (SQLite stores the full blob as TEXT).
 */

/** Progression sub-document: mining state, layer, collected items. */
export interface PgSaveProgression {
  layer: number;
  minerals: Record<string, number>;
  artifacts: string[];
  relics: string[];
  diveCount: number;
}

/** Learning sub-document: SM-2 card state, mastered facts, streaks. */
export interface PgSaveLearning {
  sm2Cards: Record<string, { interval: number; easeFactor: number; reps: number; dueDate: number }>;
  masteredFacts: string[];
  streakDays: number;
  longestStreak: number;
}

/** Dome sub-document: hub upgrades, floors, pets, farm plots. */
export interface PgSaveDome {
  upgrades: Record<string, number>;
  unlockedFloors: number[];
  pets: Array<{ species: string; stage: number }>;
  farmPlots: Array<{ crop: string | null; plantedAt: number | null }>;
}

/** Settings sub-document: audio, language, accessibility preferences. */
export interface PgSaveSettings {
  audioEnabled: boolean;
  musicVolume: number;
  sfxVolume: number;
  language: string;
  languageMode: "normal" | "categoryLock";
  ageGroup: "kid" | "teen" | "adult";
}

/** Meta sub-document: save format version, timestamps, session info. */
export interface PgSaveMeta {
  schemaVersion: number;
  clientTimestamp: number;
  sessionId: string;
  platform: string;
  appVersion: string;
}

import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";

// ── users ─────────────────────────────────────────────────────────────────────

/**
 * Registered player accounts.
 * Passwords are stored as PBKDF2 hashes — never in plaintext.
 */
export const users = sqliteTable("users", {
  /** UUID v4, generated by the application via crypto.randomUUID(). */
  id: text("id").primaryKey(),
  /** Unique email address used for login. */
  email: text("email").notNull().unique(),
  /** PBKDF2 hash in format "salt:hash" (hex-encoded). */
  passwordHash: text("password_hash").notNull(),
  /** Optional display name shown on leaderboards. */
  displayName: text("display_name"),
  /** Age bracket for content personalisation ("kid" | "teen" | "adult"). */
  ageBracket: text("age_bracket").notNull().default("adult"),
  /** Whether this account is a guest account (1 = guest, 0 = registered). */
  isGuest: integer("is_guest").notNull().default(0),
  /** Soft-delete flag (1 = deleted, 0 = active). */
  isDeleted: integer("is_deleted").notNull().default(0),
  /** Timestamp when the account was soft-deleted (epoch ms), or null if active. */
  deletedAt: integer("deleted_at"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── saves ─────────────────────────────────────────────────────────────────────

/**
 * Player save data, stored as a JSON blob.
 * Multiple save rows per user form a history; the latest is the active save.
 */
export const saves = sqliteTable("saves", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** Foreign key → users.id. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /**
   * Full PlayerSave JSON, serialised to a string.
   * Validated against schema on write; treated as opaque on read.
   */
  saveData: text("save_data").notNull(),
  /** Integer save-format version for forward/backward compatibility. */
  version: integer("version").notNull().default(1),
  /** Profile slot identifier (e.g. "default", "slot2"). */
  profileId: text("profile_id").notNull().default("default"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── leaderboards ─────────────────────────────────────────────────────────────

/**
 * Leaderboard score submissions.
 * One row per (userId, category) submission event; rankings are computed on read.
 */
export const leaderboards = sqliteTable("leaderboards", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** Foreign key → users.id. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /**
   * Category identifier, e.g. "deepest_dive", "facts_mastered", "longest_streak".
   * Not constrained at the DB level to allow new categories without migrations.
   */
  category: text("category").notNull(),
  /** Integer score for the given category. */
  score: integer("score").notNull(),
  /** Optional JSON metadata (e.g. dive depth, biome). Stored as string. */
  metadata: text("metadata"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── refresh_tokens ────────────────────────────────────────────────────────────

/**
 * Persisted refresh tokens for rotation-based invalidation.
 * On refresh, the old token is deleted and a new one is issued.
 */
export const refreshTokens = sqliteTable("refresh_tokens", {
  /** The raw refresh token string (acts as its own PK). */
  token: text("token").primaryKey(),
  /** Owner user id. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Expiry timestamp (epoch ms). Tokens past this date are invalid. */
  expiresAt: integer("expires_at").notNull(),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── analytics_events ─────────────────────────────────────────────────────────

/**
 * Client-side analytics events.
 * Lightweight event log for product analytics and debugging.
 */
export const analyticsEvents = sqliteTable("analytics_events", {
  /** UUID v4, generated by the client or server. */
  id: text("id").primaryKey(),
  /** Session identifier (opaque string, not a FK). */
  sessionId: text("session_id").notNull(),
  /** Event name, e.g. "dive_started", "quiz_answered", "fact_mastered". */
  eventName: text("event_name").notNull(),
  /** JSON-serialised event properties. */
  properties: text("properties").notNull(),
  /** Client platform ("web" | "android" | "ios"). */
  platform: text("platform"),
  /** App version string, e.g. "1.2.3". */
  appVersion: text("app_version"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── password_reset_tokens ─────────────────────────────────────────────────────

/**
 * Single-use password reset tokens.
 * Issued when a user requests a password reset; consumed on confirm.
 */
export const passwordResetTokens = sqliteTable("password_reset_tokens", {
  /** The opaque reset token (UUID v4). Acts as its own PK. */
  token: text("token").primaryKey(),
  /** Owner user id. */
  userId: text("user_id").notNull(),
  /** Expiry timestamp (epoch ms). Tokens past this date are invalid. */
  expiresAt: integer("expires_at").notNull(),
  /** Whether this token has already been consumed (1 = used, 0 = unused). */
  used: integer("used").notNull().default(0),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── fact_packs ────────────────────────────────────────────────────────────────

/**
 * Versioned fact packs for offline sync.
 * Each row is a complete snapshot of a category's facts at a given version.
 */
export const factPacks = sqliteTable("fact_packs", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** Monotonically increasing version number for this category pack. */
  version: integer("version").notNull(),
  /** Fact category this pack belongs to (e.g. "geology", "biology"). */
  category: text("category").notNull(),
  /** JSON-serialised array of fact objects. */
  packData: text("pack_data").notNull(),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── hub_visits ────────────────────────────────────────────────────────────────

/**
 * Records every visit a player makes to another player's dome hub.
 */
export const hubVisits = sqliteTable("hub_visits", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The visiting player. */
  visitorId: text("visitor_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The player whose hub was visited. */
  hostId: text("host_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Row creation timestamp (epoch ms). */
  visitedAt: integer("visited_at").notNull(),
  /** How long the visitor spent in the hub (milliseconds). */
  durationMs: integer("duration_ms").notNull().default(0),
});

// ── guestbook_entries ─────────────────────────────────────────────────────────

/**
 * Messages left by visitors in a player's dome guestbook.
 * Maximum 50 entries per host enforced at the application layer.
 */
export const guestbookEntries = sqliteTable("guestbook_entries", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The dome owner who received the message. */
  hostId: text("host_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The player who wrote the message. */
  authorId: text("author_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Denormalised display name at time of writing (survives display name changes). */
  authorName: text("author_name").notNull(),
  /** Guestbook message text, max 280 characters. */
  message: text("message").notNull(),
  /** Soft-delete flag (1 = hidden, 0 = visible). */
  isDeleted: integer("is_deleted").notNull().default(0),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── gifts ─────────────────────────────────────────────────────────────────────

/**
 * Mineral bundles or fact-link cards sent between players.
 * Unclaimed gifts expire after 30 days (enforced at application layer).
 */
export const gifts = sqliteTable("gifts", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The sending player. */
  senderId: text("sender_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The receiving player. */
  receiverId: text("receiver_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Gift category: "minerals" | "fact_link". */
  giftType: text("gift_type").notNull(),
  /** JSON payload: { amount?: number; factId?: string; factPreview?: string }. */
  payload: text("payload").notNull(),
  /** When the gift was sent (epoch ms). */
  sentAt: integer("sent_at").notNull(),
  /** Whether the receiver has claimed the gift (1 = claimed, 0 = pending). */
  claimed: integer("claimed").notNull().default(0),
  /** When the gift was claimed (epoch ms), or null if unclaimed. */
  claimedAt: integer("claimed_at"),
});

// ── friend_connections ────────────────────────────────────────────────────────

/**
 * Bidirectional friendship graph between players.
 * A friendship is canonical when status = "accepted".
 */
export const friendConnections = sqliteTable("friend_connections", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The player who sent the friend request. */
  requesterId: text("requester_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The player who received the friend request. */
  addresseeId: text("addressee_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Current state: "pending" | "accepted" | "declined" | "blocked". */
  status: text("status").notNull().default("pending"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── duels ─────────────────────────────────────────────────────────────────────

/**
 * Asynchronous knowledge duel challenges between players.
 * Both sides answer the same question set independently; results resolve
 * when both submit or the duel expires after 48 hours.
 */
export const duels = sqliteTable("duels", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The player who issued the challenge. */
  challengerId: text("challenger_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The player who was challenged. */
  opponentId: text("opponent_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /**
   * Current lifecycle state:
   * "pending" → "challenger_done" / "opponent_done" → "completed" | "timed_out" | "declined"
   */
  status: text("status").notNull().default("pending"),
  /** Amount of dust wagered by each side. */
  wagerDust: integer("wager_dust").notNull().default(0),
  /** JSON array of fact IDs used in this duel (snapshot). */
  questionFactIds: text("question_fact_ids").notNull(),
  /** The challenger's quiz score (null until submitted). */
  challengerScore: integer("challenger_score"),
  /** The opponent's quiz score (null until submitted). */
  opponentScore: integer("opponent_score"),
  /** JSON outcome: { winnerId: string | null; dustTransferred: number } (null until resolved). */
  outcome: text("outcome"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Timestamp when the duel expires (epoch ms; 48 h after creation). */
  expiresAt: integer("expires_at").notNull(),
  /** Timestamp when the duel was resolved (epoch ms), or null if unfinished. */
  completedAt: integer("completed_at"),
});

// ── artifact_cards ────────────────────────────────────────────────────────────

/**
 * Unique artifact card instances owned by players.
 * Soulbound cards cannot be traded or listed on the marketplace.
 */
export const artifactCards = sqliteTable("artifact_cards", {
  /** UUID v4, unique instance identifier. */
  instanceId: text("instance_id").primaryKey(),
  /** Current owner. */
  ownerId: text("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** ID of the fact this card represents (references facts DB). */
  factId: text("fact_id").notNull(),
  /** Rarity tier: "common" | "uncommon" | "rare" | "epic" | "legendary" | "mythic". */
  rarity: text("rarity").notNull(),
  /** When the card was originally discovered (epoch ms). */
  discoveredAt: integer("discovered_at").notNull(),
  /** 1 = card is soulbound and cannot be traded. */
  isSoulbound: integer("is_soulbound").notNull().default(0),
  /** 1 = card is currently listed on the marketplace. */
  isListed: integer("is_listed").notNull().default(0),
  /** Listing price in dust (null if not listed). */
  listPrice: integer("list_price"),
  /** Timestamp when the listing was created (epoch ms), or null if not listed. */
  listedAt: integer("listed_at"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── trade_offers ──────────────────────────────────────────────────────────────

/**
 * Direct peer-to-peer artifact card swap proposals.
 * Offers expire after 72 hours if not accepted or declined.
 */
export const tradeOffers = sqliteTable("trade_offers", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The player making the offer. */
  offererId: text("offerer_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The player receiving the offer. */
  receiverId: text("receiver_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The card instance the offerer is giving away. */
  offeredCardInstanceId: text("offered_card_instance_id")
    .notNull()
    .references(() => artifactCards.instanceId, { onDelete: "cascade" }),
  /** The card instance the offerer wants in return. */
  requestedCardInstanceId: text("requested_card_instance_id")
    .notNull()
    .references(() => artifactCards.instanceId, { onDelete: "cascade" }),
  /** Extra dust sweetener attached to the offer (can be 0). */
  additionalDust: integer("additional_dust").notNull().default(0),
  /** Offer state: "pending" | "accepted" | "declined" | "expired". */
  status: text("status").notNull().default("pending"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Timestamp when the offer expires (epoch ms; 72 h after creation). */
  expiresAt: integer("expires_at").notNull(),
  /** Timestamp when the offer was resolved (epoch ms), or null if unresolved. */
  resolvedAt: integer("resolved_at"),
});

// ── marketplace_listings ──────────────────────────────────────────────────────

/**
 * Public open-market listings for artifact cards.
 * Denormalises rarity and factId for efficient marketplace queries.
 */
export const marketplaceListings = sqliteTable("marketplace_listings", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The selling player. */
  sellerId: text("seller_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The card instance being sold. */
  instanceId: text("instance_id")
    .notNull()
    .references(() => artifactCards.instanceId, { onDelete: "cascade" }),
  /** Denormalised fact ID for category filtering. */
  factId: text("fact_id").notNull(),
  /** Denormalised rarity tier for sorting. */
  rarity: text("rarity").notNull(),
  /** Asking price in dust. */
  priceDust: integer("price_dust").notNull(),
  /** Listing state: "active" | "sold" | "cancelled". */
  status: text("status").notNull().default("active"),
  /** The player who purchased the listing (null until sold). */
  buyerId: text("buyer_id").references(() => users.id, { onDelete: "set null" }),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Timestamp when the card was sold (epoch ms), or null. */
  soldAt: integer("sold_at"),
  /** Timestamp when the listing was cancelled (epoch ms), or null. */
  cancelledAt: integer("cancelled_at"),
});

// ── guilds ────────────────────────────────────────────────────────────────────

/**
 * Player-created guilds.
 * Guild rank and GKP (Guild Knowledge Points) are recomputed periodically.
 */
export const guilds = sqliteTable("guilds", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** Unique public guild name. */
  name: text("name").notNull().unique(),
  /** 2-5 character unique tag displayed next to member names. */
  tag: text("tag").notNull().unique(),
  /** Emblem artwork index. */
  emblemId: integer("emblem_id").notNull().default(0),
  /** Short description shown on the guild profile page. */
  description: text("description").notNull().default(""),
  /** 1 = open to join requests; 0 = invite-only. */
  isOpen: integer("is_open").notNull().default(1),
  /** Current member count (denormalised, kept in sync by application). */
  memberCount: integer("member_count").notNull().default(1),
  /** Maximum number of members allowed. */
  maxMembers: integer("max_members").notNull().default(30),
  /** Global rank among all guilds (lower is better; 0 = unranked). */
  rank: integer("rank").notNull().default(0),
  /** Accumulated Guild Knowledge Points. */
  gkp: integer("gkp").notNull().default(0),
  /** The user who originally founded the guild. */
  foundedBy: text("founded_by")
    .notNull()
    .references(() => users.id, { onDelete: "restrict" }),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── guild_members ─────────────────────────────────────────────────────────────

/**
 * Guild membership roster.
 * Each player can belong to at most one guild (enforced at application layer).
 */
export const guildMembers = sqliteTable("guild_members", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The guild this membership belongs to. */
  guildId: text("guild_id")
    .notNull()
    .references(() => guilds.id, { onDelete: "cascade" }),
  /** The member player. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Member's role within the guild: "leader" | "officer" | "member". */
  role: text("role").notNull().default("member"),
  /** GKP contributed by this member (accumulated, never resets). */
  gkpContributed: integer("gkp_contributed").notNull().default(0),
  /** When the player joined this guild (epoch ms). */
  joinedAt: integer("joined_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── guild_challenges ──────────────────────────────────────────────────────────

/**
 * Weekly collaborative challenges for a guild.
 * Identified by (guild_id, challenge_type, week_start).
 */
export const guildChallenges = sqliteTable("guild_challenges", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The guild this challenge belongs to. */
  guildId: text("guild_id")
    .notNull()
    .references(() => guilds.id, { onDelete: "cascade" }),
  /** Challenge category, e.g. "facts_mastered", "dives_completed". */
  challengeType: text("challenge_type").notNull(),
  /** Required progress total to complete the challenge. */
  target: integer("target").notNull(),
  /** Current accumulated progress from all members. */
  progress: integer("progress").notNull().default(0),
  /** 1 = target has been reached this week. */
  isCompleted: integer("is_completed").notNull().default(0),
  /** Epoch ms of Monday 00:00 UTC for the week this challenge belongs to. */
  weekStart: integer("week_start").notNull(),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── guild_invites ─────────────────────────────────────────────────────────────

/**
 * Pending invitations sent to players to join a guild.
 * Invites expire after 7 days if not accepted or declined.
 */
export const guildInvites = sqliteTable("guild_invites", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The guild the invitation is for. */
  guildId: text("guild_id")
    .notNull()
    .references(() => guilds.id, { onDelete: "cascade" }),
  /** The guild leader or officer sending the invitation. */
  inviterId: text("inviter_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The player being invited. */
  inviteeId: text("invitee_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Invite state: "pending" | "accepted" | "declined" | "expired". */
  status: text("status").notNull().default("pending"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Timestamp when the invite expires (epoch ms; 7 days after creation). */
  expiresAt: integer("expires_at").notNull(),
  /** Timestamp when the invite was resolved (epoch ms), or null if unresolved. */
  resolvedAt: integer("resolved_at"),
});

// ── referrals ─────────────────────────────────────────────────────────────────

/**
 * Referral relationships: who invited whom and the reward pipeline status.
 * Each invitee can only have one referrer (unique invitee_id).
 */
export const referrals = sqliteTable("referrals", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The player who issued the referral. */
  referrerId: text("referrer_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The new player who registered via the referral. */
  inviteeId: text("invitee_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" })
    .unique(),
  /** Denormalised display name for the invitee. */
  inviteeName: text("invitee_name").notNull(),
  /** The referral code that was used during registration. */
  referralCode: text("referral_code").notNull(),
  /** Current reward pipeline status. */
  status: text("status").notNull().default("pending"),
  /** SHA-256 hash of device fingerprint for anti-abuse (never raw PII). */
  deviceHash: text("device_hash"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── leaderboard_review_queue ──────────────────────────────────────────────────

/**
 * Leaderboard scores that failed plausibility checks and are queued for
 * manual admin review before being published on the public leaderboard.
 * Approved scores are written to the leaderboards table; rejected scores
 * are silently dropped.
 */
export const leaderboardReviewQueue = sqliteTable("leaderboard_review_queue", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The submitting player. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Leaderboard category (e.g. "deepest_dive"). */
  category: text("category").notNull(),
  /** The submitted integer score (after flooring). */
  score: integer("score").notNull(),
  /** Optional JSON metadata string (nullable). */
  metadata: text("metadata"),
  /** Human-readable reason(s) the score was flagged. */
  reason: text("reason").notNull(),
  /**
   * Review decision state.
   * "pending"  — awaiting admin action.
   * "approved" — admin approved; score published.
   * "rejected" — admin rejected; score dropped.
   */
  status: text("status").notNull().default("pending"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Timestamp when the item was reviewed (epoch ms), or null if pending. */
  reviewedAt: integer("reviewed_at"),
  /** Admin-supplied note attached during review (optional). */
  reviewNote: text("review_note"),
});

// ── flagged_accounts ──────────────────────────────────────────────────────────

/**
 * Accounts that have been flagged for suspicious activity.
 * Scores from flagged accounts are voided from live leaderboards and
 * any duel scores they submit are rejected at route level.
 *
 * Flagging is soft (no ban) — accounts can be unflagged by an admin.
 */
export const flaggedAccounts = sqliteTable("flagged_accounts", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The flagged user. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" })
    .unique(),
  /** Human-readable reason for the flag (e.g. "repeated implausible scores"). */
  reason: text("reason").notNull(),
  /** Whether the flag is still active (1 = active, 0 = cleared). */
  isActive: integer("is_active").notNull().default(1),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Timestamp when the flag was cleared (epoch ms), or null if still active. */
  clearedAt: integer("cleared_at"),
});

// ── referral_rewards_log ──────────────────────────────────────────────────────

/**
 * Immutable audit trail of every reward grant made through the referral system.
 * Used for fraud detection and financial reconciliation.
 */
export const referralRewardsLog = sqliteTable("referral_rewards_log", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** The referral relationship that triggered this reward. */
  referralId: text("referral_id")
    .notNull()
    .references(() => referrals.id, { onDelete: "cascade" }),
  /** The player who received the reward. */
  recipientId: text("recipient_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Reward category, e.g. "dive_bonus", "streak_bonus", "dust_grant". */
  rewardType: text("reward_type").notNull(),
  /** JSON payload describing the reward (e.g. { dustAmount: 500 }). */
  rewardPayload: text("reward_payload").notNull(),
  /** When the reward was granted (epoch ms). */
  grantedAt: integer("granted_at").notNull(),
});

// ── Relations ─────────────────────────────────────────────────────────────────

export const usersRelations = relations(users, ({ many, one }) => ({
  saves: many(saves),
  leaderboards: many(leaderboards),
  refreshTokens: many(refreshTokens),
  hubVisitsAsVisitor: many(hubVisits, { relationName: "visitor" }),
  hubVisitsAsHost: many(hubVisits, { relationName: "host" }),
  guestbookEntriesReceived: many(guestbookEntries, { relationName: "host" }),
  guestbookEntriesWritten: many(guestbookEntries, { relationName: "author" }),
  giftsSent: many(gifts, { relationName: "sender" }),
  giftsReceived: many(gifts, { relationName: "receiver" }),
  friendRequestsSent: many(friendConnections, { relationName: "requester" }),
  friendRequestsReceived: many(friendConnections, { relationName: "addressee" }),
  duelsAsChallenger: many(duels, { relationName: "challenger" }),
  duelsAsOpponent: many(duels, { relationName: "opponent" }),
  artifactCards: many(artifactCards),
  tradeOffersAsOfferer: many(tradeOffers, { relationName: "offerer" }),
  tradeOffersAsReceiver: many(tradeOffers, { relationName: "receiver" }),
  marketplaceListings: many(marketplaceListings, { relationName: "seller" }),
  marketplacePurchases: many(marketplaceListings, { relationName: "buyer" }),
  guildsFoundedByMe: many(guilds),
  guildMemberships: many(guildMembers),
  guildInvitesSent: many(guildInvites, { relationName: "inviter" }),
  guildInvitesReceived: many(guildInvites, { relationName: "invitee" }),
  referralsIssued: many(referrals, { relationName: "referrer" }),
  referralRewardsReceived: many(referralRewardsLog),
  leaderboardReviewItems: many(leaderboardReviewQueue),
  flaggedAccount: one(flaggedAccounts, {
    fields: [users.id],
    references: [flaggedAccounts.userId],
  }),
}));

export const savesRelations = relations(saves, ({ one }) => ({
  user: one(users, { fields: [saves.userId], references: [users.id] }),
}));

export const leaderboardsRelations = relations(leaderboards, ({ one }) => ({
  user: one(users, {
    fields: [leaderboards.userId],
    references: [users.id],
  }),
}));

export const refreshTokensRelations = relations(refreshTokens, ({ one }) => ({
  user: one(users, {
    fields: [refreshTokens.userId],
    references: [users.id],
  }),
}));

// ── Social relations ──────────────────────────────────────────────────────────

export const hubVisitsRelations = relations(hubVisits, ({ one }) => ({
  visitor: one(users, {
    fields: [hubVisits.visitorId],
    references: [users.id],
    relationName: "visitor",
  }),
  host: one(users, {
    fields: [hubVisits.hostId],
    references: [users.id],
    relationName: "host",
  }),
}));

export const guestbookEntriesRelations = relations(guestbookEntries, ({ one }) => ({
  host: one(users, {
    fields: [guestbookEntries.hostId],
    references: [users.id],
    relationName: "host",
  }),
  author: one(users, {
    fields: [guestbookEntries.authorId],
    references: [users.id],
    relationName: "author",
  }),
}));

export const giftsRelations = relations(gifts, ({ one }) => ({
  sender: one(users, {
    fields: [gifts.senderId],
    references: [users.id],
    relationName: "sender",
  }),
  receiver: one(users, {
    fields: [gifts.receiverId],
    references: [users.id],
    relationName: "receiver",
  }),
}));

export const friendConnectionsRelations = relations(friendConnections, ({ one }) => ({
  requester: one(users, {
    fields: [friendConnections.requesterId],
    references: [users.id],
    relationName: "requester",
  }),
  addressee: one(users, {
    fields: [friendConnections.addresseeId],
    references: [users.id],
    relationName: "addressee",
  }),
}));

export const duelsRelations = relations(duels, ({ one }) => ({
  challenger: one(users, {
    fields: [duels.challengerId],
    references: [users.id],
    relationName: "challenger",
  }),
  opponent: one(users, {
    fields: [duels.opponentId],
    references: [users.id],
    relationName: "opponent",
  }),
}));

export const artifactCardsRelations = relations(artifactCards, ({ one, many }) => ({
  owner: one(users, { fields: [artifactCards.ownerId], references: [users.id] }),
  offeredInTrades: many(tradeOffers, { relationName: "offeredCard" }),
  requestedInTrades: many(tradeOffers, { relationName: "requestedCard" }),
  marketplaceListings: many(marketplaceListings),
}));

export const tradeOffersRelations = relations(tradeOffers, ({ one }) => ({
  offerer: one(users, {
    fields: [tradeOffers.offererId],
    references: [users.id],
    relationName: "offerer",
  }),
  receiver: one(users, {
    fields: [tradeOffers.receiverId],
    references: [users.id],
    relationName: "receiver",
  }),
  offeredCard: one(artifactCards, {
    fields: [tradeOffers.offeredCardInstanceId],
    references: [artifactCards.instanceId],
    relationName: "offeredCard",
  }),
  requestedCard: one(artifactCards, {
    fields: [tradeOffers.requestedCardInstanceId],
    references: [artifactCards.instanceId],
    relationName: "requestedCard",
  }),
}));

export const marketplaceListingsRelations = relations(marketplaceListings, ({ one }) => ({
  seller: one(users, {
    fields: [marketplaceListings.sellerId],
    references: [users.id],
    relationName: "seller",
  }),
  buyer: one(users, {
    fields: [marketplaceListings.buyerId],
    references: [users.id],
    relationName: "buyer",
  }),
  card: one(artifactCards, {
    fields: [marketplaceListings.instanceId],
    references: [artifactCards.instanceId],
  }),
}));

export const guildsRelations = relations(guilds, ({ one, many }) => ({
  founder: one(users, { fields: [guilds.foundedBy], references: [users.id] }),
  members: many(guildMembers),
  challenges: many(guildChallenges),
  invites: many(guildInvites),
}));

export const guildMembersRelations = relations(guildMembers, ({ one }) => ({
  guild: one(guilds, { fields: [guildMembers.guildId], references: [guilds.id] }),
  user: one(users, { fields: [guildMembers.userId], references: [users.id] }),
}));

export const guildChallengesRelations = relations(guildChallenges, ({ one }) => ({
  guild: one(guilds, { fields: [guildChallenges.guildId], references: [guilds.id] }),
}));

export const guildInvitesRelations = relations(guildInvites, ({ one }) => ({
  guild: one(guilds, { fields: [guildInvites.guildId], references: [guilds.id] }),
  inviter: one(users, {
    fields: [guildInvites.inviterId],
    references: [users.id],
    relationName: "inviter",
  }),
  invitee: one(users, {
    fields: [guildInvites.inviteeId],
    references: [users.id],
    relationName: "invitee",
  }),
}));

export const referralsRelations = relations(referrals, ({ one, many }) => ({
  referrer: one(users, {
    fields: [referrals.referrerId],
    references: [users.id],
    relationName: "referrer",
  }),
  invitee: one(users, {
    fields: [referrals.inviteeId],
    references: [users.id],
    relationName: "invitee",
  }),
  rewards: many(referralRewardsLog),
}));

export const referralRewardsLogRelations = relations(referralRewardsLog, ({ one }) => ({
  referral: one(referrals, {
    fields: [referralRewardsLog.referralId],
    references: [referrals.id],
  }),
  recipient: one(users, {
    fields: [referralRewardsLog.recipientId],
    references: [users.id],
  }),
}));

export const leaderboardReviewQueueRelations = relations(leaderboardReviewQueue, ({ one }) => ({
  user: one(users, {
    fields: [leaderboardReviewQueue.userId],
    references: [users.id],
  }),
}));

export const flaggedAccountsRelations = relations(flaggedAccounts, ({ one }) => ({
  user: one(users, {
    fields: [flaggedAccounts.userId],
    references: [users.id],
  }),
}));

// ── Inferred types ────────────────────────────────────────────────────────────

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Save = typeof saves.$inferSelect;
export type NewSave = typeof saves.$inferInsert;
export type Leaderboard = typeof leaderboards.$inferSelect;
export type NewLeaderboard = typeof leaderboards.$inferInsert;
export type RefreshToken = typeof refreshTokens.$inferSelect;
export type NewRefreshToken = typeof refreshTokens.$inferInsert;
export type AnalyticsEvent = typeof analyticsEvents.$inferSelect;
export type NewAnalyticsEvent = typeof analyticsEvents.$inferInsert;
export type PasswordResetToken = typeof passwordResetTokens.$inferSelect;
export type NewPasswordResetToken = typeof passwordResetTokens.$inferInsert;
export type FactPack = typeof factPacks.$inferSelect;
export type NewFactPack = typeof factPacks.$inferInsert;

// Social — Phase 22
export type HubVisit = typeof hubVisits.$inferSelect;
export type NewHubVisit = typeof hubVisits.$inferInsert;
export type GuestbookEntry = typeof guestbookEntries.$inferSelect;
export type NewGuestbookEntry = typeof guestbookEntries.$inferInsert;
export type Gift = typeof gifts.$inferSelect;
export type NewGift = typeof gifts.$inferInsert;
export type FriendConnection = typeof friendConnections.$inferSelect;
export type NewFriendConnection = typeof friendConnections.$inferInsert;
export type Duel = typeof duels.$inferSelect;
export type NewDuel = typeof duels.$inferInsert;
export type ArtifactCard = typeof artifactCards.$inferSelect;
export type NewArtifactCard = typeof artifactCards.$inferInsert;
export type TradeOffer = typeof tradeOffers.$inferSelect;
export type NewTradeOffer = typeof tradeOffers.$inferInsert;
export type MarketplaceListing = typeof marketplaceListings.$inferSelect;
export type NewMarketplaceListing = typeof marketplaceListings.$inferInsert;
export type Guild = typeof guilds.$inferSelect;
export type NewGuild = typeof guilds.$inferInsert;
export type GuildMember = typeof guildMembers.$inferSelect;
export type NewGuildMember = typeof guildMembers.$inferInsert;
export type GuildChallenge = typeof guildChallenges.$inferSelect;
export type NewGuildChallenge = typeof guildChallenges.$inferInsert;
export type GuildInvite = typeof guildInvites.$inferSelect;
export type NewGuildInvite = typeof guildInvites.$inferInsert;
export type Referral = typeof referrals.$inferSelect;
export type NewReferral = typeof referrals.$inferInsert;
export type ReferralRewardLog = typeof referralRewardsLog.$inferSelect;
export type NewReferralRewardLog = typeof referralRewardsLog.$inferInsert;

// Anti-cheat — Phase 22.7
export type LeaderboardReviewItem = typeof leaderboardReviewQueue.$inferSelect;
export type NewLeaderboardReviewItem = typeof leaderboardReviewQueue.$inferInsert;
export type FlaggedAccount = typeof flaggedAccounts.$inferSelect;
export type NewFlaggedAccount = typeof flaggedAccounts.$inferInsert;

// ── feature_flags ─────────────────────────────────────────────────────────────

/**
 * Server-side feature flags with per-user rollout control.
 * The `rollout_pct` field (0–100) determines what fraction of users see the
 * feature when no explicit user override exists.  A deterministic hash of
 * (userId + flagKey) decides whether a given user falls inside the rollout.
 */
export const featureFlags = sqliteTable('feature_flags', {
  /** Unique flag identifier, e.g. "rewarded_ads" or "ab_pioneer_timing_v2". */
  key: text('key').primaryKey(),
  /** Human-readable description of what this flag controls. */
  description: text('description').notNull().default(''),
  /** Whether this flag is globally enabled (1) or disabled (0). */
  enabled: integer('enabled').notNull().default(0),
  /** Rollout percentage 0–100 applied when enabled = 1. */
  rolloutPct: integer('rollout_pct').notNull().default(100),
  /** Epoch ms when this flag was created. */
  createdAt: integer('created_at').notNull(),
  /** Epoch ms when this flag was last modified. */
  updatedAt: integer('updated_at').notNull(),
})

// ── feature_flag_overrides ────────────────────────────────────────────────────

/**
 * Explicit per-user flag overrides.  These always take priority over rollout_pct.
 * Used for internal testers, support overrides, and force-disable on specific accounts.
 */
export const featureFlagOverrides = sqliteTable('feature_flag_overrides', {
  id: text('id').primaryKey(),
  flagKey: text('flag_key').notNull().references(() => featureFlags.key, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  /** Forced value: 1 = force-on, 0 = force-off. */
  value: integer('value').notNull(),
  createdAt: integer('created_at').notNull(),
})

// Feature flags — Phase 41.1
export type FeatureFlag = typeof featureFlags.$inferSelect;
export type NewFeatureFlag = typeof featureFlags.$inferInsert;
export type FeatureFlagOverride = typeof featureFlagOverrides.$inferSelect;
export type NewFeatureFlagOverride = typeof featureFlagOverrides.$inferInsert;
