/**
 * Drizzle ORM schema definitions for the Terra Gacha database.
 * Uses SQLite dialect for development (better-sqlite3).
 * All timestamps are stored as Unix epoch integers (milliseconds).
 */

import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";

// ── users ─────────────────────────────────────────────────────────────────────

/**
 * Registered player accounts.
 * Passwords are stored as PBKDF2 hashes — never in plaintext.
 */
export const users = sqliteTable("users", {
  /** UUID v4, generated by the application via crypto.randomUUID(). */
  id: text("id").primaryKey(),
  /** Unique email address used for login. */
  email: text("email").notNull().unique(),
  /** PBKDF2 hash in format "salt:hash" (hex-encoded). */
  passwordHash: text("password_hash").notNull(),
  /** Optional display name shown on leaderboards. */
  displayName: text("display_name"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── saves ─────────────────────────────────────────────────────────────────────

/**
 * Player save data, stored as a JSON blob.
 * Multiple save rows per user form a history; the latest is the active save.
 */
export const saves = sqliteTable("saves", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** Foreign key → users.id. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /**
   * Full PlayerSave JSON, serialised to a string.
   * Validated against schema on write; treated as opaque on read.
   */
  saveData: text("save_data").notNull(),
  /** Integer save-format version for forward/backward compatibility. */
  version: integer("version").notNull().default(1),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── leaderboards ─────────────────────────────────────────────────────────────

/**
 * Leaderboard score submissions.
 * One row per (userId, category) submission event; rankings are computed on read.
 */
export const leaderboards = sqliteTable("leaderboards", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** Foreign key → users.id. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /**
   * Category identifier, e.g. "deepest_dive", "facts_mastered", "longest_streak".
   * Not constrained at the DB level to allow new categories without migrations.
   */
  category: text("category").notNull(),
  /** Integer score for the given category. */
  score: integer("score").notNull(),
  /** Optional JSON metadata (e.g. dive depth, biome). Stored as string. */
  metadata: text("metadata"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── refresh_tokens ────────────────────────────────────────────────────────────

/**
 * Persisted refresh tokens for rotation-based invalidation.
 * On refresh, the old token is deleted and a new one is issued.
 */
export const refreshTokens = sqliteTable("refresh_tokens", {
  /** The raw refresh token string (acts as its own PK). */
  token: text("token").primaryKey(),
  /** Owner user id. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Expiry timestamp (epoch ms). Tokens past this date are invalid. */
  expiresAt: integer("expires_at").notNull(),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── Relations ─────────────────────────────────────────────────────────────────

export const usersRelations = relations(users, ({ many }) => ({
  saves: many(saves),
  leaderboards: many(leaderboards),
  refreshTokens: many(refreshTokens),
}));

export const savesRelations = relations(saves, ({ one }) => ({
  user: one(users, { fields: [saves.userId], references: [users.id] }),
}));

export const leaderboardsRelations = relations(leaderboards, ({ one }) => ({
  user: one(users, {
    fields: [leaderboards.userId],
    references: [users.id],
  }),
}));

export const refreshTokensRelations = relations(refreshTokens, ({ one }) => ({
  user: one(users, {
    fields: [refreshTokens.userId],
    references: [users.id],
  }),
}));

// ── Inferred types ────────────────────────────────────────────────────────────

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Save = typeof saves.$inferSelect;
export type NewSave = typeof saves.$inferInsert;
export type Leaderboard = typeof leaderboards.$inferSelect;
export type NewLeaderboard = typeof leaderboards.$inferInsert;
export type RefreshToken = typeof refreshTokens.$inferSelect;
export type NewRefreshToken = typeof refreshTokens.$inferInsert;
