/**
 * Drizzle ORM schema definitions for the Terra Gacha database.
 * Uses SQLite dialect for development (better-sqlite3).
 * All timestamps are stored as Unix epoch integers (milliseconds).
 */

// ── PostgreSQL jsonb migration plan (DD-V2-209) ───────────────────────────────
//
// When migrating from SQLite to PostgreSQL, the following columns should be
// converted from TEXT (JSON string) to JSONB for native indexing and querying:
//
//   saves.save_data          → jsonb  (full PlayerSave document)
//   leaderboards.metadata    → jsonb  (optional dive metadata)
//   analytics_events.properties → jsonb  (event property bag)
//   fact_packs.pack_data     → jsonb  (array of fact objects)
//
// Additionally, the saves table will be split into sub-document columns for
// efficient partial updates and field-level conflict resolution (DD-V2-214):
//
//   save_data_progression    jsonb  — { layer, minerals, artifacts, relics }
//   save_data_learning       jsonb  — { sm2Cards, masteredFacts, streaks }
//   save_data_dome           jsonb  — { upgrades, floors, pets, farm }
//   save_data_settings       jsonb  — { audio, language, accessibility }
//   save_data_meta           jsonb  — { version, clientTimestamp, sessionId }
//
// The PostgreSQL equivalent CREATE TABLE for saves would be:
//
//   CREATE TABLE saves (
//     id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
//     user_id              UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
//     version              INTEGER NOT NULL DEFAULT 1,
//     profile_id           TEXT NOT NULL DEFAULT 'default',
//     save_data_progression JSONB,
//     save_data_learning   JSONB,
//     save_data_dome       JSONB,
//     save_data_settings   JSONB,
//     save_data_meta       JSONB,
//     created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
//     updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
//   );
//   CREATE INDEX idx_saves_user_id_created ON saves(user_id, created_at DESC);
//
// Analytics columns for PostgreSQL (partitioned by month for retention):
//
//   CREATE TABLE analytics_events (
//     id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
//     session_id   TEXT NOT NULL,
//     event_name   TEXT NOT NULL,
//     properties   JSONB NOT NULL,
//     platform     TEXT,
//     app_version  TEXT,
//     user_id      UUID REFERENCES users(id) ON DELETE SET NULL,
//     created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
//   ) PARTITION BY RANGE (created_at);
//
// See server/src/db/pgReadiness.ts for migration utilities and dual-write plan.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * TypeScript types for future PostgreSQL jsonb sub-document columns.
 * These represent the decomposed structure of PlayerSave for field-level sync.
 * Not used at runtime (SQLite stores the full blob as TEXT).
 */

/** Progression sub-document: mining state, layer, collected items. */
export interface PgSaveProgression {
  layer: number;
  minerals: Record<string, number>;
  artifacts: string[];
  relics: string[];
  diveCount: number;
}

/** Learning sub-document: SM-2 card state, mastered facts, streaks. */
export interface PgSaveLearning {
  sm2Cards: Record<string, { interval: number; easeFactor: number; reps: number; dueDate: number }>;
  masteredFacts: string[];
  streakDays: number;
  longestStreak: number;
}

/** Dome sub-document: hub upgrades, floors, pets, farm plots. */
export interface PgSaveDome {
  upgrades: Record<string, number>;
  unlockedFloors: number[];
  pets: Array<{ species: string; stage: number }>;
  farmPlots: Array<{ crop: string | null; plantedAt: number | null }>;
}

/** Settings sub-document: audio, language, accessibility preferences. */
export interface PgSaveSettings {
  audioEnabled: boolean;
  musicVolume: number;
  sfxVolume: number;
  language: string;
  languageMode: "normal" | "categoryLock";
  ageGroup: "kid" | "teen" | "adult";
}

/** Meta sub-document: save format version, timestamps, session info. */
export interface PgSaveMeta {
  schemaVersion: number;
  clientTimestamp: number;
  sessionId: string;
  platform: string;
  appVersion: string;
}

import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";

// ── users ─────────────────────────────────────────────────────────────────────

/**
 * Registered player accounts.
 * Passwords are stored as PBKDF2 hashes — never in plaintext.
 */
export const users = sqliteTable("users", {
  /** UUID v4, generated by the application via crypto.randomUUID(). */
  id: text("id").primaryKey(),
  /** Unique email address used for login. */
  email: text("email").notNull().unique(),
  /** PBKDF2 hash in format "salt:hash" (hex-encoded). */
  passwordHash: text("password_hash").notNull(),
  /** Optional display name shown on leaderboards. */
  displayName: text("display_name"),
  /** Age bracket for content personalisation ("kid" | "teen" | "adult"). */
  ageBracket: text("age_bracket").notNull().default("adult"),
  /** Whether this account is a guest account (1 = guest, 0 = registered). */
  isGuest: integer("is_guest").notNull().default(0),
  /** Soft-delete flag (1 = deleted, 0 = active). */
  isDeleted: integer("is_deleted").notNull().default(0),
  /** Timestamp when the account was soft-deleted (epoch ms), or null if active. */
  deletedAt: integer("deleted_at"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── saves ─────────────────────────────────────────────────────────────────────

/**
 * Player save data, stored as a JSON blob.
 * Multiple save rows per user form a history; the latest is the active save.
 */
export const saves = sqliteTable("saves", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** Foreign key → users.id. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /**
   * Full PlayerSave JSON, serialised to a string.
   * Validated against schema on write; treated as opaque on read.
   */
  saveData: text("save_data").notNull(),
  /** Integer save-format version for forward/backward compatibility. */
  version: integer("version").notNull().default(1),
  /** Profile slot identifier (e.g. "default", "slot2"). */
  profileId: text("profile_id").notNull().default("default"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── leaderboards ─────────────────────────────────────────────────────────────

/**
 * Leaderboard score submissions.
 * One row per (userId, category) submission event; rankings are computed on read.
 */
export const leaderboards = sqliteTable("leaderboards", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** Foreign key → users.id. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /**
   * Category identifier, e.g. "deepest_dive", "facts_mastered", "longest_streak".
   * Not constrained at the DB level to allow new categories without migrations.
   */
  category: text("category").notNull(),
  /** Integer score for the given category. */
  score: integer("score").notNull(),
  /** Optional JSON metadata (e.g. dive depth, biome). Stored as string. */
  metadata: text("metadata"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── refresh_tokens ────────────────────────────────────────────────────────────

/**
 * Persisted refresh tokens for rotation-based invalidation.
 * On refresh, the old token is deleted and a new one is issued.
 */
export const refreshTokens = sqliteTable("refresh_tokens", {
  /** The raw refresh token string (acts as its own PK). */
  token: text("token").primaryKey(),
  /** Owner user id. */
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Expiry timestamp (epoch ms). Tokens past this date are invalid. */
  expiresAt: integer("expires_at").notNull(),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── analytics_events ─────────────────────────────────────────────────────────

/**
 * Client-side analytics events.
 * Lightweight event log for product analytics and debugging.
 */
export const analyticsEvents = sqliteTable("analytics_events", {
  /** UUID v4, generated by the client or server. */
  id: text("id").primaryKey(),
  /** Session identifier (opaque string, not a FK). */
  sessionId: text("session_id").notNull(),
  /** Event name, e.g. "dive_started", "quiz_answered", "fact_mastered". */
  eventName: text("event_name").notNull(),
  /** JSON-serialised event properties. */
  properties: text("properties").notNull(),
  /** Client platform ("web" | "android" | "ios"). */
  platform: text("platform"),
  /** App version string, e.g. "1.2.3". */
  appVersion: text("app_version"),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── password_reset_tokens ─────────────────────────────────────────────────────

/**
 * Single-use password reset tokens.
 * Issued when a user requests a password reset; consumed on confirm.
 */
export const passwordResetTokens = sqliteTable("password_reset_tokens", {
  /** The opaque reset token (UUID v4). Acts as its own PK. */
  token: text("token").primaryKey(),
  /** Owner user id. */
  userId: text("user_id").notNull(),
  /** Expiry timestamp (epoch ms). Tokens past this date are invalid. */
  expiresAt: integer("expires_at").notNull(),
  /** Whether this token has already been consumed (1 = used, 0 = unused). */
  used: integer("used").notNull().default(0),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
});

// ── fact_packs ────────────────────────────────────────────────────────────────

/**
 * Versioned fact packs for offline sync.
 * Each row is a complete snapshot of a category's facts at a given version.
 */
export const factPacks = sqliteTable("fact_packs", {
  /** UUID v4, generated by the application. */
  id: text("id").primaryKey(),
  /** Monotonically increasing version number for this category pack. */
  version: integer("version").notNull(),
  /** Fact category this pack belongs to (e.g. "geology", "biology"). */
  category: text("category").notNull(),
  /** JSON-serialised array of fact objects. */
  packData: text("pack_data").notNull(),
  /** Row creation timestamp (epoch ms). */
  createdAt: integer("created_at").notNull(),
  /** Row last-updated timestamp (epoch ms). */
  updatedAt: integer("updated_at").notNull(),
});

// ── Relations ─────────────────────────────────────────────────────────────────

export const usersRelations = relations(users, ({ many }) => ({
  saves: many(saves),
  leaderboards: many(leaderboards),
  refreshTokens: many(refreshTokens),
}));

export const savesRelations = relations(saves, ({ one }) => ({
  user: one(users, { fields: [saves.userId], references: [users.id] }),
}));

export const leaderboardsRelations = relations(leaderboards, ({ one }) => ({
  user: one(users, {
    fields: [leaderboards.userId],
    references: [users.id],
  }),
}));

export const refreshTokensRelations = relations(refreshTokens, ({ one }) => ({
  user: one(users, {
    fields: [refreshTokens.userId],
    references: [users.id],
  }),
}));

// ── Inferred types ────────────────────────────────────────────────────────────

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Save = typeof saves.$inferSelect;
export type NewSave = typeof saves.$inferInsert;
export type Leaderboard = typeof leaderboards.$inferSelect;
export type NewLeaderboard = typeof leaderboards.$inferInsert;
export type RefreshToken = typeof refreshTokens.$inferSelect;
export type NewRefreshToken = typeof refreshTokens.$inferInsert;
export type AnalyticsEvent = typeof analyticsEvents.$inferSelect;
export type NewAnalyticsEvent = typeof analyticsEvents.$inferInsert;
export type PasswordResetToken = typeof passwordResetTokens.$inferSelect;
export type NewPasswordResetToken = typeof passwordResetTokens.$inferInsert;
export type FactPack = typeof factPacks.$inferSelect;
export type NewFactPack = typeof factPacks.$inferInsert;
