import type { CardType } from '../../data/card-types'
import type { StatusEffectType } from '../../data/statusEffects'

// ============================================================
// Icon Path Registry
// ============================================================

// All icons are PNG files in /assets/sprites/icons/
// Generated by sprite-gen/scripts/generate-sprites.mjs from icon-registry.json

/**
 * Get the icon image path for a card type.
 * @param type - The card type (attack, shield, utility, buff, debuff, wild, heal, regen)
 * @returns The path to the card type icon (PNG format)
 */
export function getCardTypeIconPath(type: CardType | 'heal' | 'regen'): string {
	return `/assets/sprites/icons/icon_cardtype_${type}.png`
}

/**
 * Emoji fallback for card types (used when icon fails to load).
 * @param type - The card type
 * @returns An emoji representation of the card type
 */
export function getCardTypeEmoji(type: string): string {
	const EMOJI_MAP: Record<string, string> = {
		attack: '⚔️',
		shield: '🛡️',
		utility: '⭐',
		buff: '⬆️',
		debuff: '⬇️',
		wild: '💎',
		heal: '💚',
		regen: '➕',
	}
	return EMOJI_MAP[type] ?? '🃏'
}

/**
 * Get the reward altar variant icon path.
 * @param key - The reward icon key (e.g., 'arc_scroll', 'hunter_bow')
 * @returns The path to the reward icon
 */
export function getRewardIconPath(key: string): string {
	return `/assets/sprites/icons/icon_reward_${key}.png`
}

/**
 * Get the relic icon path by relic ID.
 * @param relicId - The relic identifier
 * @returns The path to the relic icon
 */
export function getRelicIconPath(relicId: string): string {
	return `/assets/sprites/icons/icon_relic_${relicId}.png`
}

/**
 * Get the V2 relic icon path (for newer relic designs).
 * @param relicId - The V2 relic identifier (with rc_ prefix, e.g., 'rc_pathfinder_boots')
 * @returns The path to the V2 relic icon
 */
export function getRelicV2IconPath(relicId: string): string {
	// V2 relics may have IDs like 'rc_pathfinder_boots' — strip prefix for filename
	const cleanId = relicId.replace(/^r[clr]_/, '')
	return `/assets/sprites/icons/icon_relic_v2_${cleanId}.png`
}

/**
 * Get the V1 relic icon path (for legacy relic designs).
 * @param relicId - The V1 relic identifier
 * @returns The path to the V1 relic icon
 */
export function getRelicV1IconPath(relicId: string): string {
	return `/assets/sprites/icons/icon_relic_v1_${relicId}.png`
}

/**
 * Get the status effect icon path.
 * @param type - The status effect type (poison, regen, strength, weakness, vulnerable, immunity)
 * @returns The path to the status effect icon
 */
export function getStatusEffectIconPath(type: StatusEffectType): string {
	return `/assets/sprites/icons/icon_status_${type}.png`
}

/**
 * Get the enemy intent icon path.
 * @param intentType - The intent type (attack, multi_attack, defend, buff, debuff, heal)
 * @returns The path to the intent icon
 */
export function getIntentIconPath(intentType: string): string {
	// Map intent types to icon paths
	const INTENT_PATH_MAP: Record<string, string> = {
		attack: '/assets/sprites/icons/icon_cardtype_attack.png',
		multi_attack: '/assets/sprites/icons/icon_intent_multi_attack.png',
		defend: '/assets/sprites/icons/icon_cardtype_shield.png',
		buff: '/assets/sprites/icons/icon_intent_buff_self.png',
		debuff: '/assets/sprites/icons/icon_intent_debuff_player.png',
		heal: '/assets/sprites/icons/icon_cardtype_heal.png',
	}
	return INTENT_PATH_MAP[intentType] ?? '/assets/sprites/icons/icon_ui_unknown.png'
}

/**
 * Get the hub navigation icon path.
 * @param navKey - The nav item key (hub, library, journal, profile, settings, social, start)
 * @returns The path to the nav icon
 */
export function getNavIconPath(navKey: string): string {
	return `/assets/sprites/icons/icon_nav_${navKey}.png`
}

/**
 * Get the hub location icon path.
 * @param locationId - The location identifier (command, lab, workshop, museum, market, archive)
 * @returns The path to the location icon
 */
export function getHubLocationIconPath(locationId: string): string {
	return `/assets/sprites/icons/icon_hub_${locationId}.png`
}

/**
 * Get the archetype icon path.
 * @param archetypeId - The archetype identifier (balanced, aggressive, defensive, control, hybrid)
 * @returns The path to the archetype icon
 */
export function getArchetypeIconPath(archetypeId: string): string {
	return `/assets/sprites/icons/icon_archetype_${archetypeId}.png`
}

/**
 * Get the data disc icon path.
 * @param discId - The disc identifier (e.g., 'disc_space', 'disc_history')
 * @returns The path to the disc icon
 */
export function getDataDiscIconPath(discId: string): string {
	// Normalize disc_* IDs to clean key
	const cleanKey = discId.replace(/^disc_/, '')
	return `/assets/sprites/icons/icon_disc_${cleanKey}.png`
}

/**
 * Get the leaderboard ranking icon path.
 * @param key - The leaderboard type (deepest_dive, facts_mastered, longest_streak, knowledge_tree, quiz_accuracy, total_dives, gold_medal, silver_medal, bronze_medal)
 * @returns The path to the leaderboard icon
 */
export function getLeaderboardIconPath(key: string): string {
	return `/assets/sprites/icons/icon_lb_${key}.png`
}

/**
 * Get the mystery event icon path.
 * @param effectType - The mystery event effect type (choice, damage, free_card, heal, nothing)
 * @returns The path to the mystery event icon
 */
export function getMysteryEventIconPath(effectType: string): string {
	return `/assets/sprites/icons/icon_mystery_${effectType}.png`
}

/**
 * Get the knowledge level icon path (tier icons for facts).
 * @param level - The knowledge level (learning, seedling, mastered)
 * @returns The path to the level icon
 */
export function getKnowledgeLevelIconPath(level: string): string {
	return `/assets/sprites/icons/icon_level_${level}.png`
}

/**
 * Get the synergy icon path.
 * @param synergyId - The synergy identifier (e.g., 'deep_diver', 'scholars_blessing')
 * @returns The path to the synergy icon
 */
export function getSynergyIconPath(synergyId: string): string {
	return `/assets/sprites/icons/icon_synergy_${synergyId}.png`
}

/**
 * Get a miscellaneous UI icon path.
 * @param elementId - The UI element identifier (e.g., 'card_fallback', 'loading', 'trophy')
 * @returns The path to the UI icon
 */
export function getUIIconPath(elementId: string): string {
	return `/assets/sprites/icons/icon_ui_${elementId}.png`
}

/**
 * Get the domain icon path (for Knowledge Library categories).
 * @param domainId - The domain identifier (e.g., 'animals_wildlife', 'space_astronomy')
 * @returns The path to the domain icon
 */
export function getDomainIconPath(domainId: string): string {
	return `/assets/sprites/icons/icon_domain_${domainId}.png`
}

// ============================================================
// Fallback emoji maps (used when icons fail to load)
// ============================================================

const NAV_EMOJI: Record<string, string> = {
	hub: '🏃',
	library: '📖',
	social: '🤝',
	settings: '⚙️',
	profile: '👤',
	journal: '📜',
	start: '▶️',
}

/**
 * Get emoji fallback for navigation items.
 * @param key - The nav item key
 * @returns An emoji representation of the nav item
 */
export function getNavEmoji(key: string): string {
	return NAV_EMOJI[key] ?? '❓'
}

const HUB_LOCATION_EMOJI: Record<string, string> = {
	command: '🏠',
	lab: '🔬',
	workshop: '⚒️',
	museum: '🏛️',
	market: '🏪',
	archive: '📚',
}

/**
 * Get emoji fallback for hub locations.
 * @param key - The location identifier
 * @returns An emoji representation of the location
 */
export function getHubLocationEmoji(key: string): string {
	return HUB_LOCATION_EMOJI[key] ?? '❓'
}

const ARCHETYPE_EMOJI: Record<string, string> = {
	balanced: '⚖️',
	aggressive: '⚔️',
	defensive: '🛡️',
	control: '🧠',
	hybrid: '🧩',
}

/**
 * Get emoji fallback for archetypes.
 * @param key - The archetype identifier
 * @returns An emoji representation of the archetype
 */
export function getArchetypeEmoji(key: string): string {
	return ARCHETYPE_EMOJI[key] ?? '❓'
}

const LEADERBOARD_EMOJI: Record<string, string> = {
	deepest_dive: '⛏️',
	facts_mastered: '🧠',
	longest_streak: '🔥',
	knowledge_tree: '🌳',
	quiz_accuracy: '🎯',
	total_dives: '🏊',
	gold_medal: '🥇',
	silver_medal: '🥈',
	bronze_medal: '🥉',
}

/**
 * Get emoji fallback for leaderboard rankings.
 * @param key - The leaderboard type
 * @returns An emoji representation of the ranking
 */
export function getLeaderboardEmoji(key: string): string {
	return LEADERBOARD_EMOJI[key] ?? '🏆'
}

const DATA_DISC_EMOJI: Record<string, string> = {
	culture: '🎭',
	geo: '🌍',
	history: '📜',
	life: '🧬',
	space: '🚀',
	tech: '💻',
}

/**
 * Get emoji fallback for data discs.
 * @param key - The disc identifier (without 'disc_' prefix)
 * @returns An emoji representation of the disc
 */
export function getDataDiscEmoji(key: string): string {
	const cleanKey = key.replace(/^disc_/, '')
	return DATA_DISC_EMOJI[cleanKey] ?? '💿'
}

const MYSTERY_EMOJI: Record<string, string> = {
	choice: '❓',
	damage: '💥',
	free_card: '🎁',
	heal: '💚',
	nothing: '⊘',
}

/**
 * Get emoji fallback for mystery events.
 * @param effectType - The mystery event effect type
 * @returns An emoji representation of the event
 */
export function getMysteryEventEmoji(effectType: string): string {
	return MYSTERY_EMOJI[effectType] ?? '❓'
}

const KNOWLEDGE_LEVEL_EMOJI: Record<string, string> = {
	casual: '🌱',
	normal: '📖',
	scholar: '🎓',
}

/**
 * Get emoji fallback for knowledge levels.
 * @param level - The knowledge level identifier
 * @returns An emoji representation of the level
 */
export function getKnowledgeLevelEmoji(level: string): string {
	return KNOWLEDGE_LEVEL_EMOJI[level] ?? '❓'
}
