"""
stitch_miner_sheet.py
---------------------
Stitches individual animation strip PNGs into a single horizontal
miner_sheet.png compatible with Phaser's spritesheet loader.

Usage:
  python stitch_miner_sheet.py --strips_dir /tmp/miner_strips --out src/assets/sprites/characters/miner_sheet.png
  python stitch_miner_sheet.py --strips_dir /tmp/miner_strips --out src/assets/sprites-hires/characters/miner_sheet.png --hires

Frame layout (see PHASE-29-CHARACTER-ANIMATION.md §29.1.1):
  idle (4) | walk_down (6) | walk_up (6) | walk_left (6) | walk_right (6) |
  mine_down (6) | mine_left (6) | mine_right (6) | hurt_fall (6) = 52 total
"""

import argparse
from pathlib import Path
from PIL import Image

FRAME_W = 32
FRAME_H = 48
HIRES_SCALE = 8  # 32→256, 48→384

# Strip names in stitching order, with their expected frame count
STRIPS = [
    ('idle',       4),
    ('walk_down',  6),
    ('walk_up',    6),
    ('walk_left',  6),
    ('walk_right', 6),   # will be generated by mirroring walk_left
    ('mine_down',  6),
    ('mine_left',  6),
    ('mine_right', 6),   # will be generated by mirroring mine_left
    ('hurt_fall',  6),
]

TOTAL_FRAMES = sum(count for _, count in STRIPS)


def load_strip(path: Path, frame_count: int, w: int, h: int) -> list[Image.Image]:
    """Load a horizontal strip image and return a list of frame Images."""
    strip = Image.open(path).convert('RGBA')
    frames = []
    for i in range(frame_count):
        frame = strip.crop((i * w, 0, (i + 1) * w, h))
        frames.append(frame)
    return frames


def mirror_frames(frames: list[Image.Image]) -> list[Image.Image]:
    """Horizontally flip a list of frames (for walk_right and mine_right)."""
    return [f.transpose(Image.FLIP_LEFT_RIGHT) for f in frames]


def stitch(strips_dir: Path, out_path: Path, hires: bool = False) -> None:
    w = FRAME_W * (HIRES_SCALE if hires else 1)
    h = FRAME_H * (HIRES_SCALE if hires else 1)

    all_frames: list[Image.Image] = []

    for name, count in STRIPS:
        if name == 'walk_right':
            # Mirror walk_left instead of loading a separate file
            left_path = strips_dir / ('walk_left_hires.png' if hires else 'walk_left.png')
            left_frames = load_strip(left_path, 6, w, h)
            all_frames.extend(mirror_frames(left_frames))
            continue

        if name == 'mine_right':
            # Mirror mine_left instead of loading a separate file
            left_path = strips_dir / ('mine_left_hires.png' if hires else 'mine_left.png')
            left_frames = load_strip(left_path, 6, w, h)
            all_frames.extend(mirror_frames(left_frames))
            continue

        suffix = '_hires' if hires else ''
        strip_path = strips_dir / f'{name}{suffix}.png'
        if not strip_path.exists():
            raise FileNotFoundError(f'Missing strip: {strip_path}')

        frames = load_strip(strip_path, count, w, h)
        all_frames.extend(frames)

    assert len(all_frames) == TOTAL_FRAMES, \
        f'Expected {TOTAL_FRAMES} frames, got {len(all_frames)}'

    # Stitch horizontally
    sheet = Image.new('RGBA', (w * TOTAL_FRAMES, h), (0, 0, 0, 0))
    for i, frame in enumerate(all_frames):
        sheet.paste(frame, (i * w, 0))

    # Quantize to 16 colors (preserves alpha)
    # Note: PIL quantize drops alpha; workaround: quantize RGB then restore alpha
    rgb = sheet.convert('RGB')
    quantized_rgb = rgb.quantize(colors=16, method=Image.Quantize.MEDIANCUT)
    quantized_rgb = quantized_rgb.convert('RGB')
    alpha = sheet.split()[3]
    quantized_rgba = Image.merge('RGBA', (*quantized_rgb.split(), alpha))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    quantized_rgba.save(out_path, 'PNG')
    print(f'Saved: {out_path}  ({sheet.width}×{sheet.height} px, {TOTAL_FRAMES} frames)')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--strips_dir', type=Path, required=True)
    parser.add_argument('--out', type=Path, required=True)
    parser.add_argument('--hires', action='store_true', help='Build 256px hi-res sheet')
    args = parser.parse_args()
    stitch(args.strips_dir, args.out, args.hires)


if __name__ == '__main__':
    main()
