/**
 * Weekly learning report aggregator.
 * Reads the player's save data from PostgreSQL (or stub from analytics events),
 * computes a weekly summary, and queues an email via emailService.
 */

export interface WeeklyReportData {
  playerDisplayName: string
  weekStartIso: string   // Monday YYYY-MM-DD
  weekEndIso: string     // Sunday YYYY-MM-DD
  totalPlayMinutes: number
  factsLearned: number
  factsMastered: number    // review state repetitions >= 5
  streakDays: number
  topCategories: Array<{ name: string; count: number }>
  wowScoreDistribution: {
    stars1: number
    stars2: number
    stars3: number
    stars4: number
    stars5: number
  }
  nextReviewDue: number    // count of facts due this week
}

/**
 * Builds a WeeklyReportData for a player from saved analytics events.
 * In production this queries the PostgreSQL analytics table.
 * Stub implementation returns plausible mock data for development.
 */
export function buildWeeklyReport(
  _playerId: string,
  _weekStartIso: string,
): WeeklyReportData {
  // Stub — production implementation queries DB
  return {
    playerDisplayName: 'Explorer',
    weekStartIso: _weekStartIso,
    weekEndIso: addDays(_weekStartIso, 6),
    totalPlayMinutes: 0,
    factsLearned: 0,
    factsMastered: 0,
    streakDays: 0,
    topCategories: [],
    wowScoreDistribution: { stars1: 0, stars2: 0, stars3: 0, stars4: 0, stars5: 0 },
    nextReviewDue: 0,
  }
}

function addDays(isoDate: string, days: number): string {
  const d = new Date(isoDate)
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

/**
 * Formats report data into a plain-text email body.
 * The HTML version (for emailService) is generated by the email template.
 */
export function formatReportPlainText(report: WeeklyReportData): string {
  const { playerDisplayName, weekStartIso, weekEndIso } = report
  const lines: string[] = [
    `Terra Gacha — Weekly Learning Report`,
    `Player: ${playerDisplayName}`,
    `Week: ${weekStartIso} to ${weekEndIso}`,
    ``,
    `Play time this week: ${report.totalPlayMinutes} minutes`,
    `New facts discovered: ${report.factsLearned}`,
    `Facts fully mastered: ${report.factsMastered}`,
    `Day streak: ${report.streakDays} days`,
    ``,
    `Top topics:`,
    ...report.topCategories.map(c => `  - ${c.name}: ${c.count} facts`),
    ``,
    `Wow Score breakdown:`,
    `  ★☆☆☆☆  ${report.wowScoreDistribution.stars1} facts`,
    `  ★★☆☆☆  ${report.wowScoreDistribution.stars2} facts`,
    `  ★★★☆☆  ${report.wowScoreDistribution.stars3} facts`,
    `  ★★★★☆  ${report.wowScoreDistribution.stars4} facts`,
    `  ★★★★★  ${report.wowScoreDistribution.stars5} facts — EXPERT!`,
    ``,
    `Facts due for review this week: ${report.nextReviewDue}`,
    ``,
    `To change report settings, open Terra Gacha → Settings → Parental Controls.`,
    `To unsubscribe: reply to this email with "UNSUBSCRIBE".`,
  ]
  return lines.join('\n')
}
